name: OpenWrt Builder

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: .config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib gperf libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone OpenWrt Source
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy Config
      run: |
        cp $CONFIG_FILE openwrt/.config

    - name: Build OpenWrt
      run: |
        cd openwrt
        make defconfig
        make -j$(nproc)

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-firmware
        path: openwrt/bin/targets/
